import type { PublicServiceCard } from './types';

export const primaryService: PublicServiceCard = {
  schemaVersion: '0.1',
  id: 'xhm_sanfu_2026',
  dataKind: 'real_public_source',
  workflowMode: 'demo',
  communityId: 'xihongmen',
  geoScope: 'xihongmen_local',
  title: '西红门医院 2026 三伏贴预约',
  shortTitle: '2026 年三伏贴服务',
  serviceType: 'healthcare',
  provider: '北京市大兴区西红门镇社区卫生服务中心（西红门医院）',
  audience: ['慢性呼吸系统疾病人群', '反复呼吸道感染人群', '体虚易感冒儿童', '60 岁以上老人'],
  eligibility: '孕妇、皮肤破损过敏、发热上火、急性疾病发作期人群不适合贴敷。',
  schedule: {
    eventStart: '2026-07-15',
    eventEnd: '2026-08-23',
  },
  location: '西红门医院三楼中医科；同兴园站、宏福园站、宏盛园站、欣清站',
  fee: '需现场缴费，金额未公开',
  capacity: null,
  registrationMethod: '线上预登记后，工作日持身份证或社保卡到西红门医院三楼中医科现场缴费确认。',
  source: {
    id: 'xhm_hospital_wechat',
    label: '西红门医院公众号',
    url: 'https://mp.weixin.qq.com/s/mV_OVjnYljiqqp4sibQyTw',
    publishedAt: '2026-06-30',
  },
  availability: {
    status: 'registration_open',
    basis: '官方公众号明确写明预约通道已开放；余量请向主办方确认。',
    verifiedAt: '2026-07-11 14:20',
  },
  missingFields: ['价格', '每日容量', '各服务站具体开放时段'],
  confidence: 'high',
  review: { status: 'ai_draft', confirmedUnknownFields: [] },
  publication: { status: 'draft' },
  demoUse: 'primary_story',
};

export const secondaryServices: PublicServiceCard[] = [
  {
    schemaVersion: '0.1',
    id: 'daxing_women_study_camp_202607',
    dataKind: 'real_public_source',
    workflowMode: 'demo',
    communityId: 'daxing',
    geoScope: 'daxing_district',
    title: '暑期“揽星寻绿访书香”研学营',
    shortTitle: '暑期研学营',
    serviceType: 'education',
    provider: '大兴区妇女儿童活动中心',
    audience: ['初一至初三学生'],
    eligibility: '每期限 20 人。',
    schedule: { eventStart: '2026-07-14', eventEnd: '2026-07-15' },
    location: '大兴区妇女儿童活动中心集合',
    fee: '免费，提供午餐',
    capacity: 40,
    registrationMethod: '原公众号文章二维码报名。',
    source: {
      id: 'daxing_women_wechat',
      label: '大兴区妇女儿童活动中心公众号',
      url: 'https://mp.weixin.qq.com/s/cU_iirDaL32X88S_UOk3_Q',
      publishedAt: '2026-07-09',
    },
    availability: {
      status: 'needs_confirmation',
      basis: '公众号发布招募，未提供实时余量。',
      verifiedAt: '2026-07-11 14:00',
    },
    missingFields: ['实时余量', '报名截止时间'],
    confidence: 'high',
    review: {
      status: 'verified',
      reviewedBy: '演示账号 · 李敏',
      reviewedAt: '2026-07-11 15:10',
      confirmedUnknownFields: ['实时余量', '报名截止时间'],
    },
    publication: { status: 'published', publishedAt: '2026-07-11 15:10' },
    demoUse: 'secondary_card',
  },
  {
    schemaVersion: '0.1',
    id: 'daxing_jobs_202607',
    dataKind: 'real_public_source',
    workflowMode: 'demo',
    communityId: 'daxing',
    geoScope: 'daxing_district_multi_site',
    title: '大兴区 2026 年 7 月招聘活动',
    shortTitle: '7 月招聘活动',
    serviceType: 'employment',
    provider: '大兴区人力资源和社会保障局及各镇街公共就业服务部门',
    audience: ['求职者', '用人单位'],
    eligibility: null,
    schedule: { eventStart: '2026-07-01', eventEnd: '2026-07-31' },
    location: '线上与各镇街现场，共 31 场',
    fee: '原文未单列费用',
    capacity: null,
    registrationMethod: '求职者通过大兴就业平台招聘会栏目参与；现场活动按附件安排。',
    source: {
      id: 'daxing_jobs_wechat',
      label: '大兴区人民政府官网',
      url: 'https://www.bjdx.gov.cn/bjsdxqrmzf/zwfw/tzgg/2356483/index.html',
      publishedAt: '2026-06-30',
    },
    availability: {
      status: 'needs_confirmation',
      basis: '区人保局公布 7 月 31 场计划；西红门专场与各场明细仍需筛选。',
      verifiedAt: '2026-07-11 13:40',
    },
    missingFields: ['31 场结构化明细', '西红门专场筛选'],
    confidence: 'high',
    review: {
      status: 'verified',
      reviewedBy: '演示账号 · 李敏',
      reviewedAt: '2026-07-11 15:20',
      confirmedUnknownFields: ['31 场结构化明细', '西红门专场筛选'],
    },
    publication: { status: 'published', publishedAt: '2026-07-11 15:20' },
    demoUse: 'secondary_card',
  },
];

export const missingFieldLabels = {
  fee: {
    label: '价格',
    value: '金额未公开',
    note: '非阻断字段，前台明确提示现场确认。',
  },
  capacity: {
    label: '每日容量',
    value: '需向主办方确认',
    note: '不把计划容量误写成剩余名额。',
  },
  stationHours: {
    label: '各服务站时段',
    value: '以各站通知为准',
    note: '居民端保留主院区已核验办理方式。',
  },
} as const;
